package kr.go.ngii.edu.main.courses.work.model;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 수업 하위 과정 모델 클래스 (과정 결과물 연결)
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "courseWorkSub")
public class CourseWorkSub implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 수업과정 아이디*/
	private int courseWorkId;

	/** 모듈 하위 과정 아이디. */
	private int moduleWorkSubId;

	/** 생성일 */
	private Date createDate;

	/** 수정일. */
	private Date modifyDate;

	public Integer getIdx() {
		return idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public int getCourseWorkId() {
		return courseWorkId;
	}

	public void setCourseWorkId(int courseWorkId) {
		this.courseWorkId = courseWorkId;
	}

	public int getModuleWorkSubId() {
		return moduleWorkSubId;
	}

	public void setModuleWorkSubId(int moduleWorkSubId) {
		this.moduleWorkSubId = moduleWorkSubId;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
}
