package kr.go.ngii.edu.main.modules.module.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 모듈 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "module")
public class Module implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 모듈명. */
	private String moduleName;

	/** 생성일. */
	private String moduleCreateDate;

	/** 수정일. */
	private String moduleModifyDate;

	/** 메타데이터. */
	private String moduleMetadata;

	/** 데이터. */
	private String moduleData;

	/**
	 * 생성자.
	 */
	public Module() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 모듈명을 설정합니다..
	 * 
	 * @param moduleName
	 *            모듈명
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * 모듈명을 가져옵니다..
	 * 
	 * @return 모듈명
	 */
	public String getModuleName() {
		return this.moduleName;
	}

	/**
	 * 생성일을 설정합니다..
	 * 
	 * @param moduleCreateDate
	 *            생성일
	 */
	public void setModuleCreateDate(String moduleCreateDate) {
		this.moduleCreateDate = moduleCreateDate;
	}

	/**
	 * 생성일을 가져옵니다..
	 * 
	 * @return 생성일
	 */
	public String getModuleCreateDate() {
		return this.moduleCreateDate;
	}

	/**
	 * 수정일을 설정합니다..
	 * 
	 * @param moduleModifyDate
	 *            수정일
	 */
	public void setModuleModifyDate(String moduleModifyDate) {
		this.moduleModifyDate = moduleModifyDate;
	}

	/**
	 * 수정일을 가져옵니다..
	 * 
	 * @return 수정일
	 */
	public String getModuleModifyDate() {
		return this.moduleModifyDate;
	}

	/**
	 * 메타데이터을 설정합니다..
	 * 
	 * @param moduleMetadata
	 *            메타데이터
	 */
	public void setModuleMetadata(String moduleMetadata) {
		this.moduleMetadata = moduleMetadata;
	}

	/**
	 * 메타데이터을 가져옵니다..
	 * 
	 * @return 메타데이터
	 */
	public String getModuleMetadata() {
		return this.moduleMetadata;
	}

	/**
	 * 데이터을 설정합니다..
	 * 
	 * @param moduleData
	 *            데이터
	 */
	public void setModuleData(String moduleData) {
		this.moduleData = moduleData;
	}

	/**
	 * 데이터을 가져옵니다..
	 * 
	 * @return 데이터
	 */
	public String getModuleData() {
		return this.moduleData;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Module other = (Module) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
