package kr.go.ngii.edu.main.modules.course.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 모듈과정컴포넌트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "moduleWorkComp")
public class ModuleWorkComp implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 공통검포넌트. */
	private Integer moduleWorkId;

	/** 모듈과정. */
	private ModuleWork compsIdmodulesWork;

	/**
	 * 생성자.
	 */
	public ModuleWorkComp() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 공통검포넌트을 설정합니다..
	 * 
	 * @param moduleWorkId
	 *            공통검포넌트
	 */
	public void setModuleWorkIdcomps(Integer moduleWorkId) {
		this.moduleWorkId = moduleWorkId;
	}

	/**
	 * 공통검포넌트을 가져옵니다..
	 * 
	 * @return 공통검포넌트
	 */
	public Integer getModuleWorkIdcomps() {
		return this.moduleWorkId;
	}

	/**
	 * 모듈과정을 설정합니다..
	 * 
	 * @param compsIdmodulesWork
	 *            모듈과정
	 */
	public void setCompsIdmodulesWork(ModuleWork compsIdmodulesWork) {
		this.compsIdmodulesWork = compsIdmodulesWork;
	}

	/**
	 * 모듈과정을 가져옵니다..
	 * 
	 * @return 모듈과정
	 */
	public ModuleWork getCompsIdmodulesWork() {
		return this.compsIdmodulesWork;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ModuleWorkComp other = (ModuleWorkComp) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
