package kr.go.ngii.edu.main.courses.team.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 팀 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "team")
public class Team implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 수업과정. */
	private Integer workId;

	/** 인증키. */
	private String authkey;


	/**
	 * 생성자.
	 */
	public Team() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 수업과정을 설정합니다..
	 * 
	 * @param workId
	 *            수업과정
	 */
	public void setWorkId(Integer workId) {
		this.workId = workId;
	}

	/**
	 * 수업과정을 가져옵니다..
	 * 
	 * @return 수업과정
	 */
	public Integer getWorkId() {
		return this.workId;
	}

	/**
	 * 인증키을 설정합니다..
	 * 
	 * @param authkey
	 *            인증키
	 */
	public void setAuthkey(String authkey) {
		this.authkey = authkey;
	}

	/**
	 * 인증키을 가져옵니다..
	 * 
	 * @return 인증키
	 */
	public String getAuthkey() {
		return this.authkey;
	}

	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Team other = (Team) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
