package kr.go.ngii.edu.main.modules.course.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 모듈과정자료 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "moduleWorkData")
public class ModuleWorkData implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 모듈. */
	private Integer moduleId;

	/** 자료명. */
	private String moduleWorkOutputName;

	/** 자료위치경로. */
	private String moduleWorkOutputPath;

	/** 수업데이터구분. */
	private String moduleWorkOutputDivision;

	/** 수업차수정보. */
	private String moduleWorkSeq;

	/**
	 * 생성자.
	 */
	public ModuleWorkData() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 모듈을 설정합니다..
	 * 
	 * @param moduleId
	 *            모듈
	 */
	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * 모듈을 가져옵니다..
	 * 
	 * @return 모듈
	 */
	public Integer getModuleId() {
		return this.moduleId;
	}

	/**
	 * 자료명을 설정합니다..
	 * 
	 * @param moduleWorkOutputName
	 *            자료명
	 */
	public void setModuleWorkOutputName(String moduleWorkOutputName) {
		this.moduleWorkOutputName = moduleWorkOutputName;
	}

	/**
	 * 자료명을 가져옵니다..
	 * 
	 * @return 자료명
	 */
	public String getModuleWorkOutputName() {
		return this.moduleWorkOutputName;
	}

	/**
	 * 자료위치경로을 설정합니다..
	 * 
	 * @param moduleWorkOutputPath
	 *            자료위치경로
	 */
	public void setModuleWorkOutputPath(String moduleWorkOutputPath) {
		this.moduleWorkOutputPath = moduleWorkOutputPath;
	}

	/**
	 * 자료위치경로을 가져옵니다..
	 * 
	 * @return 자료위치경로
	 */
	public String getModuleWorkOutputPath() {
		return this.moduleWorkOutputPath;
	}

	/**
	 * 수업데이터구분을 설정합니다..
	 * 
	 * @param moduleWorkOutputDivision
	 *            수업데이터구분
	 */
	public void setModuleWorkOutputDivision(String moduleWorkOutputDivision) {
		this.moduleWorkOutputDivision = moduleWorkOutputDivision;
	}

	/**
	 * 수업데이터구분을 가져옵니다..
	 * 
	 * @return 수업데이터구분
	 */
	public String getModuleWorkOutputDivision() {
		return this.moduleWorkOutputDivision;
	}

	/**
	 * 수업차수정보을 설정합니다..
	 * 
	 * @param moduleWorkSeq
	 *            수업차수정보
	 */
	public void setModuleWorkSeq(String moduleWorkSeq) {
		this.moduleWorkSeq = moduleWorkSeq;
	}

	/**
	 * 수업차수정보을 가져옵니다..
	 * 
	 * @return 수업차수정보
	 */
	public String getModuleWorkSeq() {
		return this.moduleWorkSeq;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ModuleWorkData other = (ModuleWorkData) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
