package kr.go.ngii.edu.main.users.model;
import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "user")
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 아이디. */
	private String userid;

	/** 패스워드. */
	private String password;

	/** 이메일. */
	private String userEmail;

	/** 이름. */
	private String userName;

	/** 사용자구분. */
	private String userDivision;

	/**
	 * 생성자.
	 */
	public User() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param userid
	 *            아이디
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getUserid() {
		return this.userid;
	}

	/**
	 * 패스워드을 설정합니다..
	 * 
	 * @param password
	 *            패스워드
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 패스워드을 가져옵니다..
	 * 
	 * @return 패스워드
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param userEmail
	 *            이메일
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getUserEmail() {
		return this.userEmail;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param userName
	 *            이름
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * 사용자구분을 설정합니다..
	 * 
	 * @param userDivision
	 *            사용자구분
	 */
	public void setUserDivision(String userDivision) {
		this.userDivision = userDivision;
	}

	/**
	 * 사용자구분을 가져옵니다..
	 * 
	 * @return 사용자구분
	 */
	public String getUserDivision() {
		return this.userDivision;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
