package kr.go.ngii.edu.main.school.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 학교 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "school")
public class School implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 학교아이디. */
	private String schoolId;

	/** 학교명. */
	private String schoolName;

	/**
	 * 생성자.
	 */
	public School() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 학교아이디을 설정합니다..
	 * 
	 * @param schoolId
	 *            학교아이디
	 */
	public void setSchoolId(String schoolId) {
		this.schoolId = schoolId;
	}

	/**
	 * 학교아이디을 가져옵니다..
	 * 
	 * @return 학교아이디
	 */
	public String getSchoolId() {
		return this.schoolId;
	}

	/**
	 * 학교명을 설정합니다..
	 * 
	 * @param schoolName
	 *            학교명
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
	 * 학교명을 가져옵니다..
	 * 
	 * @return 학교명
	 */
	public String getSchoolName() {
		return this.schoolName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		School other = (School) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
