package kr.go.ngii.edu.main.modules.comp.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 공통검포넌트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "comp")
public class Comp implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 컴포넌트명. */
	private String compName;

	/** 메타데이터. */
	private String compMetadata;

	/** 썸네일. */
	private String compThumbnail;

	/**
	 * 생성자.
	 */
	public Comp() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 컴포넌트명을 설정합니다..
	 * 
	 * @param compName
	 *            컴포넌트명
	 */
	public void setCompName(String compName) {
		this.compName = compName;
	}

	/**
	 * 컴포넌트명을 가져옵니다..
	 * 
	 * @return 컴포넌트명
	 */
	public String getCompName() {
		return this.compName;
	}

	/**
	 * 메타데이터을 설정합니다..
	 * 
	 * @param compMetadata
	 *            메타데이터
	 */
	public void setCompMetadata(String compMetadata) {
		this.compMetadata = compMetadata;
	}

	/**
	 * 메타데이터을 가져옵니다..
	 * 
	 * @return 메타데이터
	 */
	public String getCompMetadata() {
		return this.compMetadata;
	}

	/**
	 * 썸네일을 설정합니다..
	 * 
	 * @param compThumbnail
	 *            썸네일
	 */
	public void setCompThumbnail(String compThumbnail) {
		this.compThumbnail = compThumbnail;
	}

	/**
	 * 썸네일을 가져옵니다..
	 * 
	 * @return 썸네일
	 */
	public String getCompThumbnail() {
		return this.compThumbnail;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Comp other = (Comp) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
