package kr.go.ngii.edu.main.courses.course.model;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 수업 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@XmlRootElement(name = "course")
public class Course implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 고유키. */
	private Integer idx;

	/** 모듈. */
	private Integer moduleId;

	/** 수업명. */
	private String courseName;

	/** 수업설명. */
	private String courseDesc;

	/** 생성자. */
	private String courseCreateId;

	/** 생성일. */
	private String courseCreateDate;


	/**
	 * 생성자.
	 */
	public Course() {
	}

	/**
	 * 고유키을 설정합니다..
	 * 
	 * @param idx
	 *            고유키
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * 고유키을 가져옵니다..
	 * 
	 * @return 고유키
	 */
	public Integer getIdx() {
		return this.idx;
	}

	/**
	 * 모듈을 설정합니다..
	 * 
	 * @param moduleIdmodules
	 *            모듈
	 */
	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * 모듈을 가져옵니다..
	 * 
	 * @return 모듈
	 */
	public int getModuleId() {
		return this.moduleId;
	}

	/**
	 * 수업명을 설정합니다..
	 * 
	 * @param courseName
	 *            수업명
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * 수업명을 가져옵니다..
	 * 
	 * @return 수업명
	 */
	public String getCourseName() {
		return this.courseName;
	}

	/**
	 * 수업설명을 설정합니다..
	 * 
	 * @param courseDesc
	 *            수업설명
	 */
	public void setCourseDesc(String courseDesc) {
		this.courseDesc = courseDesc;
	}

	/**
	 * 수업설명을 가져옵니다..
	 * 
	 * @return 수업설명
	 */
	public String getCourseDesc() {
		return this.courseDesc;
	}

	/**
	 * 생성자을 설정합니다..
	 * 
	 * @param courseCreateId
	 *            생성자
	 */
	public void setCourseCreateId(String courseCreateId) {
		this.courseCreateId = courseCreateId;
	}

	/**
	 * 생성자을 가져옵니다..
	 * 
	 * @return 생성자
	 */
	public String getCourseCreateId() {
		return this.courseCreateId;
	}

	/**
	 * 생성일을 설정합니다..
	 * 
	 * @param courseCreateDate
	 *            생성일
	 */
	public void setCourseCreateDate(String courseCreateDate) {
		this.courseCreateDate = courseCreateDate;
	}

	/**
	 * 생성일을 가져옵니다..
	 * 
	 * @return 생성일
	 */
	public String getCourseCreateDate() {
		return this.courseCreateDate;
	}

	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idx == null) ? 0 : idx.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Course other = (Course) obj;
		if (idx == null) {
			if (other.idx != null) {
				return false;
			}
		} else if (!idx.equals(other.idx)) {
			return false;
		}
		return true;
	}

}
